# Generated by Django 3.0.7 on 2020-06-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('referral_source', models.CharField(max_length=100)),
                ('reason_interested', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_group', models.CharField(choices=[('CN', 'Control Group'), ('EX', 'Experimental Group')], default='CN', max_length=2)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.Recruit')),
            ],
        ),
    ]
