# Generated by Django 3.0.7 on 2020-06-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='age',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='phone_number',
        ),
    ]
