# Generated by Django 3.0.7 on 2020-06-10 18:01

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0002_auto_20200605_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
