# Generated by Django 3.0.7 on 2020-06-16 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0003_recruit_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_contact_date', models.DateField()),
                ('first_contact_time', models.TimeField()),
                ('end_contact_date', models.DateField()),
                ('end_contact_time', models.TimeField()),
                ('current_date', models.DateField(auto_now=True)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruits.Recruit')),
            ],
        ),
    ]
